### ISSUE TITLE
Exception on pip3 install --user dc_api

### ISSUE THREAD

**Issue by rotltoqkfrl** [song9446/dcinside-python3-api#5]
```
PS C:\Users\~\Desktop> pip3 install --user dc_api
Collecting dc_api
  Using cached https://files.pythonhosted.org/packages/fb/97/99cbc5c89cc8b33454b7c76c80e5eb25ce85766a278996030d820646ee28/dc_api-0.4.6.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\~\appdata\local\programs\python\python37-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\~\\AppData\\Local\\Temp\\pip-install-u_kr8p9q\\dc-api\\setup.py'"'"'; __file__='"'"'C:\\Users\\~\\AppData\\Local\\Temp\\pip-install-u_kr8p9q\\dc-api\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\~\AppData\Local\Temp\pip-install-u_kr8p9q\dc-api\pip-egg-info'
         cwd: C:\Users\~\AppData\Local\Temp\pip-install-u_kr8p9q\dc-api\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\~\AppData\Local\Temp\pip-install-u_kr8p9q\dc-api\setup.py", line 5, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'cp949' codec can't decode byte 0xed in position 87: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

This is what I am getting when I tried to install dc_api from my Windows machine. I think this is due to the Korean texts inside the README.md file.

I was able to fix the issue by changing line 4 from:

```
import setuptools

try:
    with open('README.md') as fh:

```
to

```
import setuptools

try:
    with open('README.md', encoding='UTF-8') as fh:
```

**Comment by song9446** [comment]
#4
