### ISSUE TITLE
글쓰기가 안됩니다.

### ISSUE THREAD

**Issue by i0rph** [song9446/dcinside-python3-api#6]
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/lib/python3.8/site-packages/dc_api.py", line 291, in write_document
    return __write_or_modify_document(board_id, title, contents, name, pw, sess)
  File "/root/.local/lib/python3.8/site-packages/dc_api.py", line 358, in __write_or_modify_document
    raise Exception(str(res))
Exception: <script>alert('잠시후 다시 이용 바랍니다.');
            location.href='https://m.dcinside.com/write/showbyrock';
            </script>`

위와같은 오류가 발생하면서 글쓰기가 않됩니다.

**Comment by eunchuldev** [comment]
제가 방금 해봤는데 잘 됐어요.. 혹시 너무 많은 트래픽을 보내셔서 아이피 차단당하신거 아닐까요?
